version: "3"

services:
    nginx-react:
        image: nginx:1.21-alpine
        container_name: nginx-react
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '80:80'
        networks:
            - nreact-net
        depends_on: 
            - react-app

    mysql-react:
        image: mariadb:10
        container_name: mysql-react
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mariadb/data:/var/lib/mysql
            - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_USER: rstack
            MYSQL_PASSWORD: rstack_pass
            MYSQL_DATABASE: rstack_db
            MYSQL_ROOT_PASSWORD: rstack_pass
        ports:
            - '3306:3306'
        restart: always
        depends_on:
            - react-app

    react-app:
        image: node:14
        container_name: react-app
        env_file: ./env
        volumes:
            - ./react-app-template/src:/usr/share/nginx/html/src
            - ./react-app-template/public:/usr/share/nginx/html/public
            - ./react-app-template/package.json:/usr/share/nginx/html/package.json
            - ./react-app-template/package-lock.json:/usr/share/nginx/html/package-lock.json
            - ./start-deploy.sh:/usr/share/nginx/start-deploy.sh
        command: /bin/sh -c "/usr/share/nginx/start-deploy.sh"
        networks:
            - nreact-net

networks:
    nreact-net:
        name: nreact-net
